Bradleykh
TrueCoders1806/taco-bells-BradleyKH pull request #1
Opened 2018-10-22 23:52 UTC by BradleyKH

2018-10-23 22:51 UTC, bdowds commented on LoggingKata.Test/TacoParserTests.cs
> +        [InlineData("hickory, dickory, dock")]
What if I passed in more than 3 values separated by commas?

2018-10-23 23:41 UTC, bdowds requested changes
Overall Good Work!

2018-10-23 23:41 UTC, bdowds commented on LoggingKata.Test/TacoParserTests.cs
> +        [InlineData("hickory, dickory, dock")]
What if I passed in more than 3 values separated by commas, or values that are not legitimate longitudes or latitudes?

2018-10-23 23:41 UTC, bdowds commented on LoggingKata/TacoParser.cs
> +
What if the longitude and latitude values passed in are not legitimate values?

2018-10-24 14:13 UTC, chipelmer commented on LoggingKata/Program.cs
> +
Small Bonus Challenge: Can you display the max distance formatted in a user-friendly way?

2018-10-25 19:23 UTC, merged